import { supabase } from "./supabase";
const PROFILE_FIELDS="id, username, display_name, avatar_url, is_verified, verification_status";
const withTimeout=(promise,ms=8000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error("Profile stats request timed out.")),ms))]);
export async function getProfile(userId){const{data,error}=await supabase.from("profiles").select("*").eq("id",userId).single();if(error)throw error;return data;}
export async function searchProfiles(query){const{data,error}=await supabase.from("profiles").select("*").or(`username.ilike.%${query}%,display_name.ilike.%${query}%`).limit(20);if(error)throw error;return data;}
export async function getProfileStats(userId){const result=await withTimeout(Promise.all([supabase.from("posts").select("id",{count:"exact",head:true}).eq("user_id",userId),supabase.from("follows").select("id",{count:"exact",head:true}).eq("following_id",userId),supabase.from("follows").select("id",{count:"exact",head:true}).eq("follower_id",userId)]));const[posts,followers,following]=result;return{postsCount:posts.count||0,followersCount:followers.count||0,followingCount:following.count||0};}
export async function followUser(followerId,followingId){if(!followerId||!followingId||followerId===followingId)return null;const{data,error}=await supabase.from("follows").upsert([{follower_id:followerId,following_id:followingId}],{onConflict:"follower_id,following_id",ignoreDuplicates:true}).select().maybeSingle();if(error)throw error;return data;}
export async function unfollowUser(followerId,followingId){const{error}=await supabase.from("follows").delete().eq("follower_id",followerId).eq("following_id",followingId);if(error)throw error;}
export async function isFollowing(followerId,followingId){const{data,error}=await supabase.from("follows").select("id").eq("follower_id",followerId).eq("following_id",followingId).maybeSingle();if(error)throw error;return!!data;}
export async function getFollowers(userId){const{data,error}=await supabase.from("follows").select(`*, profiles:follower_id(${PROFILE_FIELDS})`).eq("following_id",userId);if(error)throw error;return data?.map(f=>f.profiles);}
export async function getFollowing(userId){const{data,error}=await supabase.from("follows").select(`*, profiles:following_id(${PROFILE_FIELDS})`).eq("follower_id",userId);if(error)throw error;return data?.map(f=>f.profiles);}
let followBusy=false;
async function wireFeedFollowButton(button){if(followBusy)return;const card=button.closest(".post-card");const handle=card?.querySelector(".author-username")?.textContent?.trim().replace(/^@/,"");if(!handle)return;followBusy=true;const original=button.textContent;button.disabled=true;try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Please sign in first.");const{data:target,error:targetError}=await supabase.from("profiles").select("id").eq("username",handle).maybeSingle();if(targetError)throw targetError;if(!target?.id||target.id===user.id)return;const following=await isFollowing(user.id,target.id);if(following){await unfollowUser(user.id,target.id);button.textContent="Follow";button.classList.remove("following");}else{await followUser(user.id,target.id);button.textContent="Following";button.classList.add("following");}}catch(error){console.error("Convogram follow error",error);button.textContent=original||"Follow";}finally{button.disabled=false;followBusy=false;}}
if(typeof document!=="undefined"){document.addEventListener("click",event=>{const button=event.target.closest?.(".post-card .follow-button");if(button){event.preventDefault();event.stopPropagation();wireFeedFollowButton(button);}},true);}

let unreadTimer=null;
async function refreshMessageNavBadge(){if(typeof document==="undefined")return;const{data:{user}}=await supabase.auth.getUser().catch(()=>({data:{user:null}}));const buttons=[...document.querySelectorAll(".sidebar button")].filter(b=>b.textContent?.trim().startsWith("Messages"));if(!buttons.length)return;if(!user){buttons.forEach(b=>b.querySelector(".convogram-nav-unread")?.remove());return;}const{data,error}=await supabase.from("conversation_members").select("conversation_id,last_read_at").eq("user_id",user.id);if(error||!data?.length){buttons.forEach(b=>b.querySelector(".convogram-nav-unread")?.remove());return;}const ids=data.map(x=>x.conversation_id).filter(Boolean);const{data:messages}=await supabase.from("messages").select("conversation_id,created_at,sender_id,is_deleted").in("conversation_id",ids).neq("sender_id",user.id).eq("is_deleted",false);let total=0;for(const member of data){const read=member.last_read_at?new Date(member.last_read_at).getTime():0;total+=(messages||[]).filter(m=>m.conversation_id===member.conversation_id&&new Date(m.created_at).getTime()>read).length;}buttons.forEach(button=>{let badge=button.querySelector(".convogram-nav-unread");if(total>0){if(!badge){badge=document.createElement("span");badge.className="convogram-nav-unread";button.appendChild(badge);}badge.textContent=total>9?"9+":String(total);}else if(badge)badge.remove();});}
if(typeof document!=="undefined"){const style=document.createElement("style");style.textContent='.convogram-nav-unread{margin-left:auto;min-width:18px;height:18px;padding:0 5px;border-radius:999px;background:#ff3040;color:#fff;display:inline-flex;align-items:center;justify-content:center;font-size:10px;font-weight:800;line-height:18px;box-sizing:border-box;box-shadow:0 0 0 2px #080808}.sidebar button{position:relative}.sidebar button:has(.convogram-nav-unread) span:first-of-type{font-weight:700}';document.head.appendChild(style);const start=()=>{if(unreadTimer)return;refreshMessageNavBadge();unreadTimer=setInterval(refreshMessageNavBadge,5000);};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();}
