import { useEffect, useRef, useState } from "react";
import { Phone, Video, PhoneOff, Mic, MicOff, VideoOff, Volume2 } from "lucide-react";
import { supabase } from "../lib/supabase";
import "./CallOverlay.css";

const ICE_SERVERS = [{ urls: "stun:stun.l.google.com:19302" }, { urls: "stun:stun1.l.google.com:19302" }];
function makeCallId() { return `${crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`}`; }

export function CallOverlay({ conversationId, userId, remoteUserId, remoteName = "Contact" }) {
  const [call, setCall] = useState(null); const [incoming, setIncoming] = useState(null); const [muted, setMuted] = useState(false); const [cameraOff, setCameraOff] = useState(false); const [speaker] = useState(true); const [error, setError] = useState("");
  const channelRef = useRef(null); const pcRef = useRef(null); const localStreamRef = useRef(null); const remoteStreamRef = useRef(null); const remoteVideoRef = useRef(null); const localVideoRef = useRef(null); const pendingIceRef = useRef([]); const callRef = useRef(null);
  useEffect(() => { callRef.current = call; }, [call]);
  useEffect(() => {
    if (!conversationId || !userId || !supabase) return undefined;
    const channel = supabase.channel(`convogram-call-${conversationId}`);
    channelRef.current = channel;
    channel.on("broadcast", { event: "signal" }, async ({ payload }) => {
      if (!payload || payload.senderId === userId || (payload.toUserId && payload.toUserId !== userId)) return;
      try { await handleSignal(payload); } catch (err) { setError(err.message || "Call connection failed."); }
    }).subscribe();
    const startHandler = e => { const type = e.detail?.type; if (type && !callRef.current) startCall(type); };
    window.addEventListener("convogram-start-call", startHandler);
    return () => { window.removeEventListener("convogram-start-call", startHandler); supabase.removeChannel(channel); channelRef.current = null; cleanup(false); };
  }, [conversationId, userId, remoteUserId]);
  useEffect(() => { if (localVideoRef.current && localStreamRef.current) localVideoRef.current.srcObject = localStreamRef.current; if (remoteVideoRef.current && remoteStreamRef.current) remoteVideoRef.current.srcObject = remoteStreamRef.current; }, [call?.type, call?.status]);
  async function signal(payload) { const channel = channelRef.current; if (channel) await channel.send({ type: "broadcast", event: "signal", payload: { ...payload, senderId: userId } }); }
  function createPeer(callId, type, peerId) { const pc = new RTCPeerConnection({ iceServers: ICE_SERVERS }); pc.onicecandidate = event => { if (event.candidate) signal({ kind: "ice", callId, toUserId: peerId, candidate: event.candidate }); }; pc.ontrack = event => { if (!remoteStreamRef.current) remoteStreamRef.current = new MediaStream(); (event.streams?.[0]?.getTracks() || [event.track]).forEach(track => { if (!remoteStreamRef.current.getTracks().some(t => t.id === track.id)) remoteStreamRef.current.addTrack(track); }); if (remoteVideoRef.current) remoteVideoRef.current.srcObject = remoteStreamRef.current; }; pc.onconnectionstatechange = () => { if (pc.connectionState === "failed") setError("The call connection failed."); }; pcRef.current = pc; return pc; }
  async function getLocalMedia(type) { const constraints = type === "video" ? { audio: true, video: { facingMode: "user", width: { ideal: 1280 }, height: { ideal: 720 } } } : { audio: true }; const stream = await navigator.mediaDevices.getUserMedia(constraints); localStreamRef.current = stream; if (localVideoRef.current) localVideoRef.current.srcObject = stream; return stream; }
  async function startCall(type) { if (!remoteUserId || !conversationId) { setError("This conversation has no other participant to call."); return; } if (!navigator.mediaDevices?.getUserMedia || !window.RTCPeerConnection) { setError("Calling is not supported by this browser."); return; } try { setError(""); const callId = makeCallId(); const stream = await getLocalMedia(type); const pc = createPeer(callId, type, remoteUserId); stream.getTracks().forEach(track => pc.addTrack(track, stream)); const offer = await pc.createOffer(); await pc.setLocalDescription(offer); setCall({ callId, type, status: "calling" }); await signal({ kind: "offer", callId, type, toUserId: remoteUserId, offer }); } catch (err) { cleanup(false); setError(err.name === "NotAllowedError" ? "Microphone/camera permission was denied." : err.message || "Could not start the call."); } }
  async function handleSignal(payload) { if (payload.kind === "offer") { if (callRef.current?.callId && callRef.current.callId !== payload.callId) return; setIncoming(current => current?.callId === payload.callId ? current : { ...payload, fromUserId: payload.senderId }); return; } if (payload.kind === "answer") { if (!callRef.current || callRef.current.callId !== payload.callId) return; await pcRef.current?.setRemoteDescription(new RTCSessionDescription(payload.answer)); await flushIce(); setCall(current => current ? { ...current, status: "connected" } : current); return; } if (payload.kind === "ice") { if (!callRef.current || callRef.current.callId !== payload.callId || !pcRef.current) return; if (pcRef.current.remoteDescription) await pcRef.current.addIceCandidate(payload.candidate); else pendingIceRef.current.push(payload.candidate); return; } if (payload.kind === "hangup") { if (callRef.current?.callId === payload.callId || incoming?.callId === payload.callId) { cleanup(false); setIncoming(null); } } }
  async function flushIce() { const pc = pcRef.current; if (!pc?.remoteDescription) return; const queued = pendingIceRef.current.splice(0); for (const candidate of queued) try { await pc.addIceCandidate(candidate); } catch (_) {} }
  async function acceptIncoming() { if (!incoming) return; try { setError(""); const pending = incoming; setIncoming(null); const stream = await getLocalMedia(pending.type); const pc = createPeer(pending.callId, pending.type, pending.senderId); stream.getTracks().forEach(track => pc.addTrack(track, stream)); await pc.setRemoteDescription(new RTCSessionDescription(pending.offer)); await flushIce(); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); setCall({ callId: pending.callId, type: pending.type, status: "connected" }); await signal({ kind: "answer", callId: pending.callId, type: pending.type, toUserId: pending.senderId, answer }); } catch (err) { cleanup(false); setError(err.name === "NotAllowedError" ? "Microphone/camera permission was denied." : err.message || "Could not answer the call."); } }
  async function declineIncoming() { if (!incoming) return; await signal({ kind: "hangup", callId: incoming.callId, toUserId: incoming.senderId }); setIncoming(null); }
  async function hangup() { if (callRef.current?.callId) await signal({ kind: "hangup", callId: callRef.current.callId, toUserId: remoteUserId }); cleanup(false); }
  function cleanup(resetError = true) { pcRef.current?.close(); pcRef.current = null; localStreamRef.current?.getTracks().forEach(track => track.stop()); localStreamRef.current = null; remoteStreamRef.current = null; pendingIceRef.current = []; if (localVideoRef.current) localVideoRef.current.srcObject = null; if (remoteVideoRef.current) remoteVideoRef.current.srcObject = null; setCall(null); if (resetError) setError(""); }
  function toggleMute() { const next = !muted; localStreamRef.current?.getAudioTracks().forEach(track => { track.enabled = !next; }); setMuted(next); }
  function toggleCamera() { const next = !cameraOff; localStreamRef.current?.getVideoTracks().forEach(track => { track.enabled = !next; }); setCameraOff(next); }
  if (!conversationId) return null;
  return <>{(call || incoming) && <div className="call-layer">{incoming && !call && <div className="incoming-call-card"><div className="incoming-call-icon">{incoming.type === "video" ? <Video size={28} /> : <Phone size={28} />}</div><span>Incoming {incoming.type === "video" ? "video" : "voice"} call</span><strong>{remoteName}</strong><div className="incoming-call-actions"><button className="call-decline" onClick={declineIncoming}><PhoneOff size={20} />Decline</button><button className="call-accept" onClick={acceptIncoming}>{incoming.type === "video" ? <Video size={20} /> : <Phone size={20} />}Answer</button></div></div>}{call && <div className={`active-call ${call.type === "video" ? "video-call" : "voice-call"}`}>{call.type === "video" ? <><video ref={remoteVideoRef} className="call-remote-video" autoPlay playsInline /><video ref={localVideoRef} className="call-local-video" autoPlay muted playsInline /></> : <div className="voice-call-stage"><div className="call-avatar">{remoteName.slice(0, 1).toUpperCase()}</div><strong>{remoteName}</strong><span>{call.status === "calling" ? "Calling…" : "Connected"}</span>{speaker && <Volume2 size={18} />}</div>}<div className="call-status-pill">{call.status === "calling" ? "Calling…" : "Connected"}</div><div className="call-controls"><button className={muted ? "control-active" : ""} onClick={toggleMute}>{muted ? <MicOff /> : <Mic />}<small>{muted ? "Unmute" : "Mute"}</small></button>{call.type === "video" && <button className={cameraOff ? "control-active" : ""} onClick={toggleCamera}>{cameraOff ? <VideoOff /> : <Video />}<small>{cameraOff ? "Camera" : "Video"}</small></button>}<button className="call-end" onClick={hangup}><PhoneOff /><small>End</small></button></div></div>}{error && <div className="call-error">{error}</div>}</div>}{error && !call && !incoming && <div className="call-toast" onClick={() => setError("")}>{error}</div>}</>;
}
