import { useEffect, useRef, useState } from "react";
import { Camera, Shield, UserMinus, UserPlus, Users } from "lucide-react";
import { addCommunityMember, getCommunityMembers, removeCommunityMember, searchCommunityPeople, setCommunityMemberRole, updateCommunity, uploadCommunityAvatar } from "../lib/communities";

export default function CommunityManagement({ community, userId, onUpdated }) {
 const [members,setMembers]=useState([]),[q,setQ]=useState(""),[results,setResults]=useState([]),[name,setName]=useState(community.name||""),[description,setDescription]=useState(community.description||""),[error,setError]=useState(""); const file=useRef(null);
 const load=async()=>{try{setMembers(await getCommunityMembers(community.id));}catch(e){setError(e.message||"Unable to load members.")}}; useEffect(()=>{load()},[community.id]);
 const find=async e=>{const v=e.target.value;setQ(v);if(!v.trim()){setResults([]);return}try{setResults(await searchCommunityPeople(v))}catch(e){setError(e.message||"Search failed.")}};
 const add=async p=>{try{const m=await addCommunityMember(community.id,p.id);setMembers(x=>x.some(v=>v.user_id===m.user_id)?x:[...x,m]);setQ("");setResults([])}catch(e){setError(e.message||"Could not add member.")}};
 const remove=async m=>{if(m.user_id===community.owner_id)return;try{await removeCommunityMember(community.id,m.user_id);setMembers(x=>x.filter(v=>v.user_id!==m.user_id))}catch(e){setError(e.message||"Could not remove member.")}};
 const admin=async m=>{if(m.user_id===community.owner_id)return;try{const v=await setCommunityMemberRole(community.id,m.user_id,m.role==="admin"?"member":"admin");setMembers(x=>x.map(a=>a.user_id===m.user_id?{...a,...v}:a))}catch(e){setError(e.message||"Could not change role.")}};
 const save=async e=>{e.preventDefault();try{const v=await updateCommunity(community.id,{name:name.trim(),description:description.trim()||null});onUpdated(v)}catch(e){setError(e.message||"Could not save community.")}};
 const avatar=async e=>{const f=e.target.files?.[0];if(!f)return;try{const v=await uploadCommunityAvatar(community.id,userId,f);onUpdated(v)}catch(e){setError(e.message||"Could not change DP.")}e.target.value=""};
 return <section className="community-management"><div className="community-management-title"><Shield size={18}/><div><strong>Community controls</strong><span>Owner controls for your community.</span></div></div>{error&&<div className="global-error">{error}</div>}<div className="community-avatar-control"><div className="community-icon large">{community.avatar_url?<img src={community.avatar_url} alt=""/>:community.name?.charAt(0).toUpperCase()}</div><button type="button" className="secondary-button" onClick={()=>file.current?.click()}><Camera size={15}/> Change DP</button><input ref={file} type="file" accept="image/*" hidden onChange={avatar}/></div><form className="community-create-fields" onSubmit={save}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Community name" required/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Community description"/><button className="primary-button" type="submit">Save changes</button></form><div className="community-management-title"><UserPlus size={18}/><div><strong>Add people</strong><span>Search by username or name.</span></div></div><div className="community-member-search"><UserPlus size={15}/><input value={q} onChange={find} placeholder="Search people to add"/></div>{results.length>0&&<div className="community-search-results">{results.map(p=><button type="button" key={p.id} onClick={()=>add(p)}><span>{p.display_name||p.username}</span><small>@{p.username}</small><UserPlus size={15}/></button>)}</div>}<div className="community-management-title"><Users size={18}/><div><strong>Members ({members.length})</strong><span>Remove members or make admins.</span></div></div><div className="community-member-list">{members.map(m=><div className="community-member-row" key={m.user_id}><div className="mini-avatar">{(m.profiles?.display_name||m.profiles?.username||"M").charAt(0).toUpperCase()}</div><div><strong>{m.profiles?.display_name||m.profiles?.username||"Member"}</strong><small>@{m.profiles?.username||"member"} · {m.user_id===community.owner_id?"owner":m.role}</small></div>{m.user_id===community.owner_id?<span className="member-owner">Owner</span>:<div className="member-actions"><button type="button" onClick={()=>admin(m)} title="Toggle admin"><Shield size={14}/></button><button type="button" onClick={()=>remove(m)} title="Remove member"><UserMinus size={14}/></button></div>}</div>)}</div></section>;
}
