import { useEffect, useState } from "react";
import { Check, Compass, Plus, Users, X } from "lucide-react";
import { createCommunity, createCommunityPost, getCommunities, getCommunityPosts, getUserCommunities, joinCommunity, leaveCommunity } from "../lib/communities";
import "./CommunitiesPanel.css";

function friendlyCommunityError(err) {
  const message = err?.message || "";
  if (message.includes("schema cache") || message.includes("Could not find the table 'public.communities'")) return "Communities are being connected to the database. Please apply the latest Convogram Supabase migration, then refresh.";
  return message || "Unable to load communities.";
}

export function CommunitiesPanel({ userId }) {
  const [communities, setCommunities] = useState([]), [mine, setMine] = useState([]), [selected, setSelected] = useState(null), [posts, setPosts] = useState([]), [draft, setDraft] = useState(""), [createOpen, setCreateOpen] = useState(false), [name, setName] = useState(""), [description, setDescription] = useState(""), [loading, setLoading] = useState(true), [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const [all, joined] = await Promise.all([getCommunities(50), getUserCommunities(userId)]); setCommunities(all || []); setMine(joined || []); } catch (err) { setError(friendlyCommunityError(err)); } finally { setLoading(false); } }
  useEffect(() => { if (userId) load(); }, [userId]);
  async function openCommunity(community) { setSelected(community); setError(""); try { setPosts(await getCommunityPosts(community.id, 30) || []); } catch (err) { setError(friendlyCommunityError(err)); } }
  const joinedIds = new Set(mine.map((item) => item.id));
  async function toggleJoin(community) { setError(""); try { if (joinedIds.has(community.id)) { await leaveCommunity(community.id, userId); setMine((current) => current.filter((item) => item.id !== community.id)); } else { await joinCommunity(community.id, userId); setMine((current) => [...current, { ...community, userRole: "member" }]); } } catch (err) { setError(friendlyCommunityError(err)); } }
  async function publishPost(event) { event.preventDefault(); if (!draft.trim() || !selected || !joinedIds.has(selected.id)) return; try { const created = await createCommunityPost(selected.id, userId, draft.trim()); setPosts((current) => [created, ...current]); setDraft(""); } catch (err) { setError(friendlyCommunityError(err)); } }
  async function handleCreate(event) { event.preventDefault(); if (!name.trim()) return; try { const created = await createCommunity(userId, name.trim(), description.trim()); const hydrated = { ...created, profiles: { display_name: "You" }, community_members: [{ count: 1 }] }; setCommunities((current) => [hydrated, ...current]); setMine((current) => [{ ...created, userRole: "owner" }, ...current]); setName(""); setDescription(""); setCreateOpen(false); await openCommunity(hydrated); } catch (err) { setError(friendlyCommunityError(err)); } }
  return <div className="community-workspace">
    {error && <div className="global-error" role="alert"><span>{error}</span><button onClick={() => setError("")} aria-label="Dismiss"><X size={15}/></button></div>}
    <header className="community-toolbar"><div className="community-heading"><span className="eyebrow">YOUR SPACES</span><h2>Communities</h2></div><div className="community-toolbar-actions"><button className="secondary-button" onClick={load}><Compass size={16}/> Discover</button><button className="primary-button small" onClick={() => setCreateOpen((value) => !value)}><Plus size={16}/> Create</button></div></header>
    {createOpen && <form className="community-create-inline" onSubmit={handleCreate}><div className="community-create-copy"><span className="eyebrow">NEW SPACE</span><h3>Create community</h3><p>Start a space for people to connect and share.</p></div><div className="community-create-fields"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Community name" required/><textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="What is this community about?"/><div className="community-create-actions"><button type="button" className="secondary-button" onClick={() => setCreateOpen(false)}>Cancel</button><button className="primary-button" type="submit">Create community</button></div></div></form>}
    {loading ? <div className="community-loading"><Users size={28}/><p>Loading communities…</p></div> : <div className="community-layout"><aside className="community-list"><div className="community-list-title">All communities</div>{communities.map((community) => <button key={community.id} className={`community-list-item ${selected?.id === community.id ? "selected" : ""}`} onClick={() => openCommunity(community)}><div className="community-icon">{community.name?.charAt(0).toUpperCase()}</div><div><strong>{community.name}</strong><span>{community.community_members?.[0]?.count || 0} members</span></div></button>)}{!communities.length && <div className="empty-state"><Users size={28}/><p>No communities yet.</p></div>}</aside><section className="community-detail">{selected ? <><header className="community-detail-head"><div><span className="eyebrow">COMMUNITY</span><h2>{selected.name}</h2><p>{selected.description || "A place to connect and share."}</p></div><button className={joinedIds.has(selected.id) ? "secondary-button" : "primary-button small"} onClick={() => toggleJoin(selected)}>{joinedIds.has(selected.id) ? <><Check size={16}/> Joined</> : "Join"}</button></header>{joinedIds.has(selected.id) && <form className="community-composer" onSubmit={publishPost}><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder={`Share something with ${selected.name}...`}/><button type="submit" aria-label="Publish"><Plus size={17}/></button></form>}<div className="community-posts">{posts.map((post) => <article className="community-post" key={post.id}><div className="mini-avatar">{(post.profiles?.display_name || "C").charAt(0).toUpperCase()}</div><div><strong>{post.profiles?.display_name || "Member"}</strong><small>@{post.profiles?.username || "member"}</small><p>{post.content}</p></div></article>)}{!posts.length && <div className="empty-state"><Users size={28}/><h3>No posts yet</h3><p>Start the first conversation.</p></div>}</div></> : <div className="community-empty"><Users size={36}/><h2>Find your people</h2><p>Discover communities, join conversations, or create a space of your own.</p><div className="community-empty-actions"><button className="secondary-button" onClick={load}><Compass size={16}/> Discover communities</button><button className="primary-button" onClick={() => setCreateOpen(true)}><Plus size={16}/> Create a community</button></div></div>}</section></div>}
  </div>;
}
