import { useEffect, useMemo, useRef, useState } from "react";
import { ChevronLeft, ImagePlus, Mic, Send, Square, Phone, Video, CornerUpLeft, Trash2, Copy, X, Pencil, Pin, Smile } from "lucide-react";
import { getConversationDetails, getMessages, sendMessage, subscribeToConversation, deleteMessage, editMessage, addMessageReaction, removeMessageReaction, toggleMessagePin } from "../lib/messages";
import { uploadMessageMedia, uploadVoiceMessage } from "../lib/storage";
import { supabase } from "../lib/supabase";
import { VerifiedBadge } from "./VerifiedBadge";
import EmojiPicker from "emoji-picker-react";
import "./MessagesPanel.css";
import "./MessagesPanel.chat-fix.css";
import "./MessagesPanel.bottom-safe-area.css";

const REACTIONS = ["💪", "👍", "😂", "😊", "❤️"];
function formatTime(value) { try { return new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }); } catch { return ""; } }
function profileName(profile) { return profile?.display_name || profile?.username || "Convogram user"; }
function messageLabel(m) { if (!m) return ""; if (m.is_deleted) return "Message deleted"; if (m.message_type === "image") return "Photo"; if (m.message_type === "video") return "Video"; if (m.message_type === "audio") return "Voice message"; return m.content || "Attachment"; }
function MessageBody({ message }) {
  if (message.is_deleted) return <em className="convogram-chat-deleted">Message deleted</em>;
  if (message.message_type === "image" && message.media_url) return <img className="convogram-chat-image" src={message.media_url} alt="Sent photo" loading="lazy" />;
  if (message.message_type === "video" && message.media_url) return <video className="convogram-chat-video" src={message.media_url} controls playsInline preload="metadata" />;
  if (message.message_type === "audio" && message.media_url) return <audio className="convogram-chat-audio" src={message.media_url} controls preload="metadata" />;
  return <span>{message.content || "Attachment"}</span>;
}
function ReplyPreview({ message, mine }) { if (!message) return null; return <div className={`convogram-chat-reply-preview ${mine ? "mine" : ""}`}><strong>{message.profiles?.display_name || "Reply"}</strong><span>{messageLabel(message)}</span></div>; }

export function MessagesPanel({ userId, initialConversationId = null, onBack, onChatOpen }) {
  const [conversation, setConversation] = useState(null), [peer, setPeer] = useState(null), [messages, setMessages] = useState([]), [draft, setDraft] = useState("");
  const [loading, setLoading] = useState(true), [sending, setSending] = useState(false), [uploading, setUploading] = useState(false), [recording, setRecording] = useState(false), [error, setError] = useState("");
  const [replyingTo, setReplyingTo] = useState(null), [menuMessage, setMenuMessage] = useState(null), [editingMessage, setEditingMessage] = useState(null), [reactionOpen, setReactionOpen] = useState(false), [swipe, setSwipe] = useState({ id: null, x: 0 });
  const pinnedMessage = useMemo(() => messages.find(m => m.is_pinned) || null, [messages]);
  const streamRef = useRef(null), composerRef = useRef(null), fileRef = useRef(null), recorderRef = useRef(null), chunksRef = useRef([]);
  const longPressRef = useRef({ timer: null, messageId: null, triggered: false }), touchRef = useRef({ id: null, startX: 0, startY: 0 });

  useEffect(() => { onChatOpen?.(true); return () => onChatOpen?.(false); }, [onChatOpen]);
  const clearLongPress = () => { if (longPressRef.current.timer) clearTimeout(longPressRef.current.timer); longPressRef.current = { timer: null, messageId: null, triggered: false }; };
  const startLongPress = message => { clearLongPress(); longPressRef.current = { messageId: message.id, triggered: false, timer: setTimeout(() => { longPressRef.current.triggered = true; setMenuMessage(message); setReactionOpen(false); setSwipe({ id: null, x: 0 }); }, 520) }; };
  const handleTouchStart = (e, message) => { const t = e.touches?.[0]; if (!t) return; touchRef.current = { id: message.id, startX: t.clientX, startY: t.clientY }; startLongPress(message); };
  const handleTouchMove = (e, message) => { const t = e.touches?.[0], s = touchRef.current; if (!t || s.id !== message.id) return; const dx = t.clientX - s.startX, dy = Math.abs(t.clientY - s.startY); if (Math.abs(dx) > 10 || dy > 10) clearLongPress(); if (dx > 0 && dy < 60) setSwipe({ id: message.id, x: Math.min(dx, 78) }); };
  const handleTouchEnd = (e, message) => { const t = e.changedTouches?.[0], s = touchRef.current; const dx = t ? t.clientX - s.startX : 0, dy = t ? Math.abs(t.clientY - s.startY) : 999; const longPressed = longPressRef.current.triggered; clearLongPress(); if (!longPressed && s.id === message.id && dx >= 64 && dx > dy * 1.25) { setReplyingTo(message); requestAnimationFrame(() => composerRef.current?.focus()); } setSwipe({ id: null, x: 0 }); touchRef.current = { id: null, startX: 0, startY: 0 }; };

  useEffect(() => { let cancelled = false; async function load() { if (!initialConversationId || !userId) { setLoading(false); return; } setLoading(true); setError(""); try {
    const details = await getConversationDetails(initialConversationId); if (cancelled) return; setConversation(details);
    const { data: members, error: memberError } = await supabase.from("conversation_members").select("user_id").eq("conversation_id", initialConversationId); if (memberError) throw memberError;
    const peerId = (members || []).map(m => m.user_id).find(id => id && id !== userId); if (peerId) { const { data: profile } = await supabase.from("profiles").select("id,username,display_name,avatar_url,is_verified").eq("id", peerId).maybeSingle(); if (!cancelled) setPeer(profile || null); }
    const data = await getMessages(initialConversationId, 100, userId); if (!cancelled) setMessages(Array.isArray(data) ? data : []);
  } catch (e) { if (!cancelled) { setError(e?.message || "Unable to load this conversation."); setMessages([]); } } finally { if (!cancelled) setLoading(false); } } load(); return () => { cancelled = true; }; }, [initialConversationId, userId]);
  useEffect(() => { if (!initialConversationId) return undefined; return subscribeToConversation(initialConversationId, incoming => setMessages(prev => prev.some(m => m.id === incoming.id) ? prev : [...prev, incoming].sort((a,b) => new Date(a.created_at)-new Date(b.created_at))), updated => setMessages(prev => prev.map(m => m.id === updated.id ? { ...m, ...updated } : m))); }, [initialConversationId]);
  useEffect(() => { const el = streamRef.current; if (el) requestAnimationFrame(() => { el.scrollTop = el.scrollHeight; }); }, [messages.length, loading]);

  const title = useMemo(() => conversation?.type === "group" ? conversation.name || "Group conversation" : profileName(peer), [conversation, peer]);
  const sendText = async e => { e.preventDefault(); const text = draft.trim(); if (!text || !initialConversationId || !userId || sending) return; try { setSending(true); setError("");
    if (editingMessage) { const updated = await editMessage(editingMessage.id, userId, text); setMessages(prev => prev.map(m => m.id === updated.id ? { ...m, ...updated } : m)); setEditingMessage(null); }
    else { const sent = await sendMessage(initialConversationId, userId, text, "text", null, replyingTo?.id || null); setMessages(prev => prev.some(m => m.id === sent.id) ? prev : [...prev, { ...sent, profiles: { id: userId, display_name: "You" }, reply_to: replyingTo || null }]); setReplyingTo(null); }
    setDraft(""); requestAnimationFrame(() => composerRef.current?.focus());
  } catch (e2) { setError(e2?.message || "Could not save message."); } finally { setSending(false); } };
  const chooseMedia = () => fileRef.current?.click();
  const handleMedia = async e => { const file = e.target.files?.[0]; if (!file || !initialConversationId || !userId || uploading) return; try { setUploading(true); const uploaded = await uploadMessageMedia(file, userId); const sent = await sendMessage(initialConversationId, userId, null, uploaded.mediaType, uploaded.url, replyingTo?.id || null); setMessages(prev => [...prev, sent]); setReplyingTo(null); } catch (e2) { setError(e2?.message || "Could not send media."); } finally { setUploading(false); if (fileRef.current) fileRef.current.value = ""; } };
  const startRecording = async () => { if (recording) { recorderRef.current?.stop(); return; } if (!navigator.mediaDevices?.getUserMedia || !window.MediaRecorder) { setError("Voice messages are not available on this device."); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const recorder = new MediaRecorder(stream); chunksRef.current=[]; recorder.ondataavailable=e=>{if(e.data?.size)chunksRef.current.push(e.data)}; recorder.onstop=async()=>{try{setUploading(true);const blob=new Blob(chunksRef.current,{type:recorder.mimeType||"audio/webm"});const file=new File([blob],`voice-${Date.now()}.webm`,{type:blob.type||"audio/webm"});const uploaded=await uploadVoiceMessage(file,userId);const sent=await sendMessage(initialConversationId,userId,null,"audio",uploaded.url,replyingTo?.id||null);setMessages(prev=>[...prev,sent]);setReplyingTo(null)}catch(e2){setError(e2?.message||"Could not send voice message.")}finally{stream.getTracks().forEach(t=>t.stop());setUploading(false);setRecording(false)}}; recorderRef.current=recorder; recorder.start(); setRecording(true); } catch(e2){setError(e2?.message||"Microphone permission is required.")} };
  const copyMessage = async m => { if (m.content && navigator.clipboard?.writeText) try { await navigator.clipboard.writeText(m.content); } catch (_) {} setMenuMessage(null); };
  const deleteOwnMessage = async m => { if (m.sender_id !== userId) return; try { const updated=await deleteMessage(m.id); setMessages(prev=>prev.map(x=>x.id===updated.id?{...x,...updated}:x)); } catch(e2){setError(e2?.message||"Could not delete message.")} finally{setMenuMessage(null)} };
  const chooseReaction = async reaction => { const m=menuMessage; if (!m) return; try { const existing=(m.message_reactions||[]).find(r=>r.user_id===userId&&r.reaction===reaction); if(existing){await removeMessageReaction(m.id,userId,reaction); setMessages(prev=>prev.map(x=>x.id===m.id?{...x,message_reactions:(x.message_reactions||[]).filter(r=>r.id!==existing.id)}:x));} else {const added=await addMessageReaction(m.id,userId,reaction); setMessages(prev=>prev.map(x=>x.id===m.id?{...x,message_reactions:[...(x.message_reactions||[]),added]}:x));} } catch(e2){setError(e2?.message||"Could not react to message.")} finally{setMenuMessage(null);setReactionOpen(false)} };
  const pinMessage = async m => { try { const updated=await toggleMessagePin(m.id,!m.is_pinned); setMessages(prev=>prev.map(x=>x.id===m.id?{...x,is_pinned:updated?.is_pinned ?? !m.is_pinned}:x)); } catch(e2){setError(e2?.message||"Could not pin message.")} finally{setMenuMessage(null)} };
  const beginEdit = m => { if(m.sender_id!==userId || m.message_type!=="text" || m.is_deleted) return; setEditingMessage(m); setDraft(m.content||""); setMenuMessage(null); setReactionOpen(false); requestAnimationFrame(()=>composerRef.current?.focus()); };
  const scrollToPinned = () => { if (!pinnedMessage) return; const el = streamRef.current?.querySelector(`[data-message-id="${pinnedMessage.id}"]`); el?.scrollIntoView({ behavior: "smooth", block: "center" }); };

  return <div className="messages-panel chat-open convogram-stable-chat"><style>{`
    .convogram-stable-chat{position:fixed;inset:0;background:#080808;color:#fff;z-index:50;display:flex;flex-direction:column;padding-top:env(safe-area-inset-top,0px);padding-bottom:max(env(safe-area-inset-bottom,0px),56px)}
    .convogram-stable-chat-head{height:62px;min-height:62px;background:#0b0b0b;border-bottom:1px solid #202020;display:flex;align-items:center;gap:10px;padding:0 12px}.convogram-stable-chat-back{width:40px;height:40px;border:0;background:transparent;color:#fff;display:grid;place-items:center;border-radius:50%}.convogram-stable-chat-avatar{width:38px;height:38px;border-radius:50%;overflow:hidden;background:#181818;border:1px solid #292929;display:grid;place-items:center;flex:0 0 auto}.convogram-stable-chat-avatar img{width:100%;height:100%;object-fit:cover}.convogram-stable-chat-title{min-width:0;flex:1;display:flex;flex-direction:column;gap:2px}.convogram-stable-chat-name{display:flex;align-items:center;gap:3px;font-size:15px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.convogram-stable-chat-status{font-size:11px;color:#777}.convogram-stable-chat-actions{display:flex;gap:2px}.convogram-stable-chat-action{width:38px;height:38px;border:0;background:transparent;color:#ddd;display:grid;place-items:center;border-radius:50%}
    .convogram-stable-chat-body{min-height:0;flex:1;display:flex;flex-direction:column;background:#0a0a0a}.convogram-stable-chat-stream{flex:1;min-height:0;overflow-y:auto;padding:14px 12px 18px;display:flex;flex-direction:column;gap:8px;overscroll-behavior:contain}.convogram-chat-state{margin:auto;max-width:320px;text-align:center;color:#777;display:flex;flex-direction:column;gap:7px;align-items:center}.convogram-chat-state strong{color:#eee;font-size:14px}.convogram-chat-state span{font-size:12px}.convogram-chat-error{margin:8px 12px;padding:9px 11px;border-radius:10px;background:#2a1515;color:#ffb2b2;font-size:12px;border:1px solid #4a2222}
    .convogram-chat-row{display:flex;width:100%;transition:transform 120ms ease;position:relative}.convogram-chat-row.mine{justify-content:flex-end}.convogram-chat-bubble{max-width:min(78%,420px);padding:9px 11px;border-radius:16px;background:#181818;border:1px solid #272727;box-sizing:border-box;position:relative}.convogram-chat-row.mine .convogram-chat-bubble{background:#145c8c;border-color:#1879b7}.convogram-chat-content{font-size:14px;line-height:1.4;overflow-wrap:anywhere}.convogram-chat-meta{margin-top:4px;font-size:9px;opacity:.65;text-align:right}.convogram-chat-image,.convogram-chat-video{max-width:100%;max-height:280px;border-radius:12px;display:block}.convogram-chat-audio{width:min(240px,100%)}.convogram-chat-deleted{opacity:.65}.convogram-chat-reply-preview{margin:-2px -2px 7px;padding:6px 8px;border-left:3px solid #20a4f3;border-radius:6px;background:#111;color:#aaa;display:flex;flex-direction:column;gap:2px;font-size:10px}.convogram-chat-reply-preview strong{color:#ddd;font-size:10px}.convogram-chat-reply-preview span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.convogram-chat-reply-preview.mine{background:rgba(0,0,0,.18)}
    .convogram-message-reactions{display:flex;gap:3px;flex-wrap:wrap;margin-top:5px}.convogram-reaction-chip{border:1px solid #303030;background:#101010;color:#fff;border-radius:12px;padding:2px 6px;font-size:11px;line-height:18px}.convogram-stable-reply-bar{display:flex;align-items:center;gap:8px;padding:8px 10px;background:#101010;border-top:1px solid #202020}.convogram-stable-reply-copy{min-width:0;flex:1;display:flex;flex-direction:column;gap:2px}.convogram-stable-reply-copy strong{font-size:11px;color:#20a4f3}.convogram-stable-reply-copy span{font-size:11px;color:#aaa;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    .convogram-pinned-banner{width:100%;box-sizing:border-box;border:0;border-bottom:1px solid #242424;background:#111;color:#fff;display:flex;align-items:center;gap:9px;padding:8px 12px;text-align:left}.convogram-pinned-banner:active{background:#191919}.convogram-pinned-banner-icon{width:30px;height:30px;border-radius:9px;background:#182a35;color:#20a4f3;display:grid;place-items:center;flex:0 0 auto}.convogram-pinned-banner-copy{min-width:0;flex:1;display:flex;flex-direction:column;gap:2px}.convogram-pinned-banner-copy strong{font-size:11px;color:#20a4f3}.convogram-pinned-banner-copy span{font-size:12px;color:#ccc;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.convogram-pinned-banner-arrow{transform:rotate(180deg);color:#777}.convogram-emoji-panel{position:absolute;right:10px;bottom:62px;width:min(300px,calc(100vw - 20px));padding:10px;background:#151515;border:1px solid #303030;border-radius:16px;box-shadow:0 12px 36px rgba(0,0,0,.55);display:grid;grid-template-columns:repeat(5,1fr);gap:5px;z-index:80}.convogram-emoji-button{height:42px;border:0;border-radius:10px;background:#202020;font-size:22px;color:#fff}.convogram-emoji-button:active{background:#303030}.convogram-stable-composer-wrap{padding:8px 10px;background:#0b0b0b;border-top:1px solid #202020;position:relative}.convogram-stable-composer{display:flex;align-items:flex-end;gap:7px;background:#151515;border:1px solid #292929;border-radius:22px;padding:5px}.convogram-stable-icon{width:38px;height:38px;border:0;background:transparent;color:#bbb;display:grid;place-items:center;border-radius:50%;flex:0 0 auto}.convogram-stable-input{flex:1;min-width:0;border:0;outline:0;background:transparent;color:#fff;resize:none;font:inherit;font-size:14px;padding:9px 4px;max-height:110px}.convogram-stable-send{width:38px;height:38px;border:0;border-radius:50%;background:#20a4f3;color:#fff;display:grid;place-items:center;flex:0 0 auto}
    .convogram-chat-menu-backdrop{position:fixed;inset:0;z-index:89;background:rgba(0,0,0,.25)}.convogram-chat-menu{position:fixed;z-index:90;left:12px;right:12px;bottom:calc(env(safe-area-inset-bottom,0px) + 74px);background:#151515;border:1px solid #303030;border-radius:16px;box-shadow:0 14px 40px rgba(0,0,0,.55);padding:6px;display:flex;flex-direction:column}.convogram-chat-menu button{display:flex;align-items:center;gap:10px;padding:13px 12px;background:transparent;color:#fff;border:0;border-radius:11px;text-align:left;font-size:14px}.convogram-chat-menu button:active{background:#232323}.convogram-chat-menu .danger{color:#ff8f8f}.convogram-reaction-row{display:flex;justify-content:space-between;align-items:center;padding:7px 6px;border-bottom:1px solid #292929;margin-bottom:3px}.convogram-reaction-button{border:0;background:#222;border-radius:13px;width:42px;height:38px;font-size:20px;display:grid;place-items:center}.convogram-pinned-mark{position:absolute;right:7px;top:-9px;background:#151515;border:1px solid #303030;border-radius:10px;padding:2px 4px;color:#20a4f3;display:grid;place-items:center}
    @media(max-width:600px){.convogram-chat-bubble{max-width:82%}}
  `}</style>
  <header className="convogram-stable-chat-head"><button type="button" className="convogram-stable-chat-back" aria-label="Back" onClick={onBack}><ChevronLeft size={23}/></button><div className="convogram-stable-chat-avatar">{peer?.avatar_url?<img src={peer.avatar_url} alt=""/>:<span>●</span>}</div><div className="convogram-stable-chat-title"><div className="convogram-stable-chat-name">{title}<VerifiedBadge verified={peer?.is_verified} size={16}/></div><span className="convogram-stable-chat-status">{conversation?.type === "group" ? "Group chat" : "Messages"}</span></div><div className="convogram-stable-chat-actions"><button type="button" className="convogram-stable-chat-action" aria-label="Voice call"><Phone size={18}/></button><button type="button" className="convogram-stable-chat-action" aria-label="Video call"><Video size={18}/></button></div></header>
  <div className="convogram-stable-chat-body">{pinnedMessage && <button type="button" className="convogram-pinned-banner" onClick={scrollToPinned} aria-label="Jump to pinned message"><span className="convogram-pinned-banner-icon"><Pin size={15}/></span><span className="convogram-pinned-banner-copy"><strong>Pinned message</strong><span>{messageLabel(pinnedMessage)}</span></span><ChevronLeft size={15} className="convogram-pinned-banner-arrow" /></button>}<div className="convogram-stable-chat-stream" ref={streamRef}>
    {loading?<div className="convogram-chat-state"><strong>Loading messages…</strong><span>Please wait</span></div>:messages.length===0?<div className="convogram-chat-state"><strong>No messages yet</strong><span>Send a message to start the conversation.</span></div>:messages.map(message=>{const mine=message.sender_id===userId,offset=swipe.id===message.id?swipe.x:0;const reactions=message.message_reactions||[];return <div key={message.id} data-message-id={message.id} className={`convogram-chat-row ${mine?"mine":""}`} style={{transform:`translateX(${offset}px)`}}>{offset>28&&<CornerUpLeft size={16} style={{position:"absolute",left:3,top:"50%",transform:"translateY(-50%)",color:"#20a4f3"}}/>}<div className="convogram-chat-bubble" onContextMenu={e=>{e.preventDefault();setMenuMessage(message);setReactionOpen(false)}} onTouchStart={e=>handleTouchStart(e,message)} onTouchMove={e=>handleTouchMove(e,message)} onTouchEnd={e=>handleTouchEnd(e,message)} onTouchCancel={()=>{clearLongPress();setSwipe({id:null,x:0})}}>{message.is_pinned&&<span className="convogram-pinned-mark" title="Pinned"><Pin size={11}/></span>}{message.reply_to&&<ReplyPreview message={message.reply_to} mine={mine}/>}<div className="convogram-chat-content"><MessageBody message={message}/></div><div className="convogram-chat-meta">{formatTime(message.created_at)}{message.updated_at&&message.updated_at!==message.created_at?" · edited":""}</div>{reactions.length>0&&<div className="convogram-message-reactions">{REACTIONS.filter(r=>reactions.some(x=>x.reaction===r)).map(r=><button key={r} type="button" className="convogram-reaction-chip" onClick={()=>{setMenuMessage(message);chooseReaction(r)}}>{r} {reactions.filter(x=>x.reaction===r).length}</button>)}</div>}</div></div>})}
  </div>{error&&<div className="convogram-chat-error">{error}</div>}
  {(replyingTo||editingMessage)&&<div className="convogram-stable-reply-bar">{editingMessage?<Pencil size={17} color="#20a4f3"/>:<CornerUpLeft size={17} color="#20a4f3"/>}<div className="convogram-stable-reply-copy"><strong>{editingMessage?"Editing message":`Replying to ${replyingTo?.sender_id===userId?"yourself":profileName(peer)}`}</strong><span>{messageLabel(editingMessage||replyingTo)}</span></div><button type="button" className="convogram-stable-icon" aria-label="Cancel" onClick={()=>{setReplyingTo(null);setEditingMessage(null);setDraft("")}}><X size={18}/></button></div>}
  <div className="convogram-stable-composer-wrap">{reactionOpen && <div className="convogram-emoji-panel" role="dialog" aria-label="Emoji picker"><EmojiPicker onEmojiClick={(emojiData) => { setDraft(d => d + emojiData.emoji); requestAnimationFrame(() => composerRef.current?.focus()); }} width="100%" height="100%" previewConfig={{ showPreview: false }} skinTonesDisabled={false} searchDisabled={false} lazyLoadEmojis={true} /></div>}<input ref={fileRef} type="file" accept="image/*,video/*" hidden onChange={handleMedia}/><form className="convogram-stable-composer" onSubmit={sendText}><button type="button" className="convogram-stable-icon" aria-label="Emoji" onClick={() => setReactionOpen(v => !v)}><Smile size={20}/></button><button type="button" className="convogram-stable-icon" aria-label="Add media" onClick={chooseMedia} disabled={uploading}><ImagePlus size={20}/></button><textarea ref={composerRef} className="convogram-stable-input" rows={1} value={draft} onChange={e=>setDraft(e.target.value)} placeholder={editingMessage?"Edit message":replyingTo?"Write a reply…":"Message"}/>{draft.trim()?<button type="submit" className="convogram-stable-send" aria-label={editingMessage?"Save edit":"Send"} disabled={sending}><Send size={18}/></button>:<button type="button" className="convogram-stable-icon" aria-label={recording?"Stop recording":"Record voice message"} onClick={startRecording}>{recording?<Square size={19}/>:<Mic size={20}/>}</button>}</form></div></div>
  {menuMessage&&<><div className="convogram-chat-menu-backdrop" onClick={()=>setMenuMessage(null)}/><div className="convogram-chat-menu" role="menu"><div className="convogram-reaction-row">{REACTIONS.map(r=><button key={r} type="button" className="convogram-reaction-button" aria-label={`React ${r}`} onClick={()=>chooseReaction(r)}>{r}</button>)}</div><button type="button" onClick={()=>{setReplyingTo(menuMessage);setMenuMessage(null);requestAnimationFrame(()=>composerRef.current?.focus())}}><CornerUpLeft size={18}/> Reply</button>{menuMessage.sender_id===userId&&!menuMessage.is_deleted&&menuMessage.message_type==="text"&&<button type="button" onClick={()=>beginEdit(menuMessage)}><Pencil size={18}/> Edit message</button>}<button type="button" onClick={()=>pinMessage(menuMessage)}><Pin size={18}/> {menuMessage.is_pinned?"Unpin message":"Pin message"}</button>{menuMessage.content&&<button type="button" onClick={()=>copyMessage(menuMessage)}><Copy size={18}/> Copy</button>}{menuMessage.sender_id===userId&&!menuMessage.is_deleted&&<button type="button" className="danger" onClick={()=>deleteOwnMessage(menuMessage)}><Trash2 size={18}/> Delete</button>}</div></>}
  </div>;
}
export default MessagesPanel;
