import React from 'react';
import { Plus, Loader, AlertCircle, Heart, MessageCircle, Eye, X, Send, ChevronLeft, ChevronRight, MoreHorizontal } from 'lucide-react';
import { recordMomentView, isMomentLikedByUser, likeMoment, unlikeMoment, getMomentViewers, getMomentComments, addMomentComment } from '../lib/moments';
import './MomentsRow.css';

function Avatar({profile, className=''}) { return profile?.avatar_url ? <img src={profile.avatar_url} className={className} alt=""/> : <div className={`${className} fallback-avatar`}>{(profile?.display_name||profile?.username||'C').slice(0,1).toUpperCase()}</div>; }

export function MomentsRow({ moments = [], currentUserId, onAddMoment, onViewMoment, loading, error }) {
  const [selected,setSelected]=React.useState(null),[index,setIndex]=React.useState(0),[liked,setLiked]=React.useState(false),[likeCount,setLikeCount]=React.useState(0),[viewCount,setViewCount]=React.useState(0),[viewers,setViewers]=React.useState([]),[comments,setComments]=React.useState([]),[comment,setComment]=React.useState(''),[commentsOpen,setCommentsOpen]=React.useState(false),[viewersOpen,setViewersOpen]=React.useState(false),[busy,setBusy]=React.useState(false);
  const open = async (moment,i) => { setSelected(moment);setIndex(i);setCommentsOpen(false);setViewersOpen(false);setLikeCount(moment.moment_likes?.[0]?.count||0);setViewCount(moment.moment_views?.[0]?.count||0);setLiked(false);setComments([]);setViewers([]); try { if(moment.user_id!==currentUserId) await recordMomentView(moment.id,currentUserId); const [isLiked,cs]=await Promise.all([isMomentLikedByUser(moment.id,currentUserId),getMomentComments(moment.id)]);setLiked(isLiked);setComments(cs||[]);const vs=await getMomentViewers(moment.id);setViewers(vs||[]);setViewCount(vs?.length||moment.moment_views?.[0]?.count||0); } catch(e){console.error(e);} onViewMoment?.(moment,i); };
  const close=()=>setSelected(null);
  const move=dir=>{const n=index+dir;if(n>=0&&n<moments.length)open(moments[n],n);};
  const toggleLike=async()=>{if(!selected||busy)return;setBusy(true);try{if(liked){await unlikeMoment(selected.id,currentUserId);setLiked(false);setLikeCount(c=>Math.max(0,c-1));}else{await likeMoment(selected.id,currentUserId);setLiked(true);setLikeCount(c=>c+1);}}catch(e){console.error(e);}finally{setBusy(false);}};
  const submitComment=async e=>{e.preventDefault();if(!comment.trim()||!selected||busy)return;setBusy(true);try{const c=await addMomentComment(selected.id,currentUserId,comment.trim());setComments(x=>[...x,c]);setComment('');}catch(e){console.error(e);}finally{setBusy(false);}};
  if(error)return <div className="moments-error"><AlertCircle size={24}/><p>Failed to load Moments</p></div>;
  if(loading)return <div className="moments-loading"><Loader className="spinning"/></div>;
  return <>
    <div className="moments-row"><div className="moment-item add-moment" onClick={onAddMoment}><div className="moment-circle"><Plus size={24}/></div><span>Your Moment</span></div>{moments.map((moment,i)=><div key={moment.id} className="moment-item" onClick={()=>open(moment,i)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')open(moment,i)}}><img src={moment.media_url} alt="Moment" className="moment-preview"/><div className="moment-overlay"><Avatar profile={moment.profiles} className="moment-avatar"/><span className="moment-name">{moment.profiles?.display_name||'Moment'}</span></div></div>)}</div>
    {selected&&<div className="story-viewer" onClick={close}><div className="story-shell" onClick={e=>e.stopPropagation()}><div className="story-progress"><span/></div><div className="story-head"><Avatar profile={selected.profiles} className="story-avatar"/><div className="story-author"><b>{selected.profiles?.display_name||'Moment'}</b><small>@{selected.profiles?.username||''}</small></div><button onClick={close}><X size={22}/></button></div><div className="story-media">{selected.media_type==='video'?<video src={selected.media_url} controls autoPlay playsInline/>:<img src={selected.media_url} alt={selected.caption||'Moment'}/>}<button className="story-arrow left" disabled={index===0} onClick={()=>move(-1)}><ChevronLeft/></button><button className="story-arrow right" disabled={index===moments.length-1} onClick={()=>move(1)}><ChevronRight/></button></div>{selected.caption&&<div className="story-caption">{selected.caption}</div>}<div className="story-actions"><button onClick={toggleLike} className={liked?'liked':''}><Heart size={22} fill={liked?'currentColor':'none'}/><span>{likeCount}</span></button><button onClick={()=>setCommentsOpen(v=>!v)}><MessageCircle size={22}/><span>{comments.length}</span></button><button onClick={()=>setViewersOpen(v=>!v)}><Eye size={22}/><span>{viewCount}</span></button><button><MoreHorizontal size={22}/></button></div>{commentsOpen&&<div className="story-sheet"><div className="sheet-title"><b>Comments</b><span>{comments.length}</span><button onClick={()=>setCommentsOpen(false)}><X size={18}/></button></div><div className="story-comments">{comments.length?comments.map(c=><div className="story-comment" key={c.id}><Avatar profile={c.profiles} className="comment-avatar"/><div><b>{c.profiles?.username||c.profiles?.display_name||'user'}</b><p>{c.content}</p><small>{new Date(c.created_at).toLocaleString()}</small></div></div>):<div className="sheet-empty">No comments yet. Be the first.</div>}</div><form className="story-comment-form" onSubmit={submitComment}><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a comment..."/><button disabled={!comment.trim()||busy}><Send size={18}/></button></form></div>}{viewersOpen&&<div className="story-sheet"><div className="sheet-title"><b>Views</b><span>{viewCount}</span><button onClick={()=>setViewersOpen(false)}><X size={18}/></button></div><div className="story-comments">{viewers.length?viewers.map(v=><div className="story-comment" key={v.id}><Avatar profile={v.profiles} className="comment-avatar"/><div><b>{v.profiles?.username||v.profiles?.display_name||'viewer'}</b><small>Viewed your Moment</small></div></div>):<div className="sheet-empty">No viewers yet.</div>}</div></div>}</div></div>}
  </>;
}
