import React from 'react';
import { Plus, Loader, AlertCircle, Heart, Eye, X, MoreHorizontal, MessageCircle, Repeat2 } from 'lucide-react';
import { recordMomentView, isMomentLikedByUser, likeMoment, unlikeMoment, getMomentViewers, createMoment } from '../lib/moments';
import { getDirectConversation, createConversation, sendMessage } from '../lib/messages';
import { VerifiedBadge } from './VerifiedBadge';
import './MomentsRow.css';

function Avatar({profile, className=''}) { return profile?.avatar_url ? <img src={profile.avatar_url} className={className} alt=""/> : <div className={`${className} fallback-avatar`}>{(profile?.display_name||profile?.username||'C').slice(0,1).toUpperCase()}</div>; }

export function MomentsRow({ moments = [], currentUserId, onAddMoment, loading, error }) {
  const [selected,setSelected]=React.useState(null),[index,setIndex]=React.useState(0),[liked,setLiked]=React.useState(false),[likeCount,setLikeCount]=React.useState(0),[viewCount,setViewCount]=React.useState(0),[viewers,setViewers]=React.useState([]),[viewersOpen,setViewersOpen]=React.useState(false),[busy,setBusy]=React.useState(false),[paused,setPaused]=React.useState(false),[progress,setProgress]=React.useState(0);
  const timerRef=React.useRef(null),touchRef=React.useRef({x:0,y:0});
  const isOwner = selected?.user_id === currentUserId;
  const clearTimer=React.useCallback(()=>{if(timerRef.current){clearInterval(timerRef.current);timerRef.current=null;}},[]);
  const open=React.useCallback(async(moment,i)=>{clearTimer();setSelected(moment);setIndex(i);setViewersOpen(false);setLikeCount(moment.moment_likes?.[0]?.count||0);setViewCount(moment.moment_views?.[0]?.count||0);setLiked(false);setViewers([]);setProgress(0);setPaused(false);try{if(moment.user_id!==currentUserId)await recordMomentView(moment.id,currentUserId);const isLiked=await isMomentLikedByUser(moment.id,currentUserId);setLiked(isLiked);if(moment.user_id===currentUserId){const vs=await getMomentViewers(moment.id);setViewers(vs||[]);setViewCount(vs?.length||moment.moment_views?.[0]?.count||0);}}catch(e){console.error(e);}},[clearTimer,currentUserId]);
  const close=React.useCallback(()=>{clearTimer();setSelected(null);setProgress(0);},[clearTimer]);
  const move=React.useCallback(dir=>{const n=index+dir;if(n<0){setProgress(0);return;}if(n>=moments.length){close();return;}open(moments[n],n);},[close,index,moments,open]);
  React.useEffect(()=>()=>clearTimer(),[clearTimer]);
  React.useEffect(()=>{if(!selected||paused||viewersOpen)return;clearTimer();const duration=selected.media_type==='video'?Math.max(5,selected.duration||5):5;const step=100/(duration*20);timerRef.current=setInterval(()=>setProgress(p=>{const next=p+step;if(next>=100){clearTimer();setTimeout(()=>move(1),0);return 100;}return next;}),50);return clearTimer;},[selected,index,paused,viewersOpen,move,clearTimer]);
  const toggleLike=async()=>{if(!selected||busy)return;setBusy(true);try{if(liked){await unlikeMoment(selected.id,currentUserId);setLiked(false);setLikeCount(c=>Math.max(0,c-1));}else{await likeMoment(selected.id,currentUserId);setLiked(true);setLikeCount(c=>c+1);}}catch(e){console.error(e);}finally{setBusy(false);}};
  const replyToMoment=async()=>{if(!selected||!currentUserId||selected.user_id===currentUserId||busy)return;const text=window.prompt('Reply to this Moment');if(!text?.trim())return;setBusy(true);try{let conversation=await getDirectConversation(currentUserId,selected.user_id);if(!conversation)conversation=await createConversation(currentUserId,'direct',null,null,[selected.user_id]);await sendMessage(conversation.id,currentUserId,text.trim(),'text');}catch(e){console.error(e);window.alert('Could not send the reply. Please try again.');}finally{setBusy(false);}};
  const reshareMoment=async()=>{if(!selected||!currentUserId||selected.user_id===currentUserId||busy)return;setBusy(true);try{const originalAuthor=selected.profiles?.username||selected.profiles?.display_name||'user';const caption=selected.caption?`Reshared from @${originalAuthor}: ${selected.caption}`:`Reshared from @${originalAuthor}`;await createMoment(currentUserId,selected.media_url,selected.media_type,caption);window.alert('Moment reshared to your Moments.');}catch(e){console.error(e);window.alert('Could not reshare this Moment. Please try again.');}finally{setBusy(false);}};
  const handleTouchStart=e=>{touchRef.current={x:e.touches[0].clientX,y:e.touches[0].clientY};setPaused(true);};
  const handleTouchEnd=e=>{setPaused(false);const dx=e.changedTouches[0].clientX-touchRef.current.x;const dy=e.changedTouches[0].clientY-touchRef.current.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy))move(dx<0?1:-1);else if(dy>100)close();};
  if(error)return <div className="moments-error"><AlertCircle size={24}/><p>Failed to load Moments</p></div>;
  if(loading)return <div className="moments-loading"><Loader className="spinning"/></div>;
  return <>
    <div className="moments-row"><div className="moment-item add-moment" onClick={onAddMoment}><div className="moment-circle"><Plus size={24}/></div><span>Your Moment</span></div>{moments.map((moment,i)=><div key={moment.id} className="moment-item" onClick={()=>open(moment,i)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')open(moment,i)}}><img src={moment.media_url} alt="Moment" className="moment-preview"/><div className="moment-overlay"><Avatar profile={moment.profiles} className="moment-avatar"/><span className="moment-name">{moment.profiles?.display_name||'Moment'}<VerifiedBadge verified={moment.profiles?.is_verified} verificationStatus={moment.profiles?.verification_status} size={14}/></span></div></div>)}</div>
    {selected&&<div className="story-viewer" onClick={close}><div className="story-shell" onClick={e=>e.stopPropagation()} onTouchStart={handleTouchStart} onTouchEnd={handleTouchEnd}>
      <div className="story-progress">{moments.map((m,i)=><span key={m.id}><i className={i<index?'done':''} style={{width:i<index?'100%':i===index?`${progress}%`:'0%'}}/></span>)}</div>
      <div className="story-head"><Avatar profile={selected.profiles} className="story-avatar"/><div className="story-author"><b>{selected.profiles?.display_name||'Moment'}<VerifiedBadge verified={selected.profiles?.is_verified} verificationStatus={selected.profiles?.verification_status} size={16}/></b><small>@{selected.profiles?.username||''} · 24h</small></div><button onClick={()=>setPaused(p=>!p)}>{paused?'▶':'Ⅱ'}</button><button onClick={close}><X size={22}/></button></div>
      <div className="story-media"><button className="story-tap story-tap-left" onClick={()=>move(-1)} aria-label="Previous story"/><button className="story-tap story-tap-right" onClick={()=>move(1)} aria-label="Next story"/>{selected.media_type==='video'?<video src={selected.media_url} autoPlay={!paused} playsInline onEnded={()=>move(1)}/>:<img src={selected.media_url} alt={selected.caption||'Moment'}/>}</div>
      {selected.caption&&<div className="story-caption">{selected.caption}</div>}
      <div className="story-actions">{isOwner?<><button onClick={toggleLike} className={liked?'liked':''}><Heart size={22} fill={liked?'currentColor':'none'}/><span>{likeCount}</span></button><button onClick={()=>setViewersOpen(v=>!v)}><Eye size={22}/><span>{viewCount}</span></button><button onClick={()=>setViewersOpen(v=>!v)}><MoreHorizontal size={22}/></button></>:<><button onClick={replyToMoment} disabled={busy}><MessageCircle size={22}/><span>Reply</span></button><button onClick={reshareMoment} disabled={busy}><Repeat2 size={22}/><span>Reshare</span></button></>}</div>
      {isOwner&&viewersOpen&&<div className="story-sheet"><div className="sheet-title"><b>Views</b><span>{viewCount}</span><button onClick={()=>setViewersOpen(false)}><X size={18}/></button></div><div className="story-comments">{viewers.length?viewers.map(v=><div className="story-comment" key={v.id}><Avatar profile={v.profiles} className="comment-avatar"/><div><b>{v.profiles?.username||v.profiles?.display_name||'viewer'}<VerifiedBadge verified={v.profiles?.is_verified} verificationStatus={v.profiles?.verification_status} size={15}/></b><small>Viewed your Moment</small></div></div>):<div className="sheet-empty">No viewers yet.</div>}</div></div>}
    </div></div>}
  </>;
}
